### ISSUE TITLE
Error in calculating Taxonomic rank

### ISSUE THREAD

**Issue by giuseppebenvenuto** [ivlachos/agamemnon#3]
Hello,
thank you for creating this interesting tool.
I was able to install all dependencies without problems.
In order to analyze my samples, first I decided to check the entire workflow based on your use case in Wiki starting from fastq files recommended.
Following the Wiki step by step, I got this error message launching `snakemake --snakefile AGAMEMNON --cores 24 --resources mem_mb=140000` (Mapping and quantification were ok):

```
Job 4: *** [Calculating Taxonomic ranks... | Threads: 1] - 14:44:43

Traceback (most recent call last):
  File "/home/agamemnon/scripts/./getTaxonomy.py", line 204, in <module>
    _lineage = buildTaxonomy(args.taxonomyFdir + '/nodes.dmp', args.taxonomyFdir + '/names.dmp', _taxid_Accessions)
  File "/home/agamemnon/scripts/./getTaxonomy.py", line 93, in buildTaxonomy
    tempLineage.append(nodes[parent][1] + '|' + names[parent] + '|' + parent)
KeyError: '1546149'
[Wed Apr  6 14:54:35 2022]
Error in rule taxonomic_ranks:
    jobid: 4
    output: /home/agamemnon/results/ERR688534/taxonomic_ranks/results.tab
    shell:     
		/home/agamemnon/scripts/./getTaxonomy.py -qf /home/agamemnon/results/ERR688534/cedar/quant.sf -tfd /home/agamemnon/Taxonomy/ -al agamemnon -od /home/agamemnon/results/ERR688534/taxonomic_ranks
```

Could you please help me?
Thanks in advance

Giuseppe

**Comment by gskoufos** [comment]
Hi Giuseppe,

Thanks for your interest in our work!

I followed the Use case in order to reproduce your error but everything worked great for me.

I suspect that the error is due to the NCBI taxonomy files!

Are you sure that you executed exactly what is written in the "Microbial reference preparation" and "Download NCBI taxonomy & Prepare auxiliary files for AGAMEMNON" sections?

Can you please send me some details about your "Taxonomy" folder? What files are in there? 

Please if it's possible, send me the number of lines per file too.

I just want to compare your Taxonomy directory with mine; sometimes NCBI's servers are unstable and you end up downloading files with missing data!

Best,
Giorgos

**Comment by giuseppebenvenuto** [comment]
Hi,
thank you for your quick reply.
I'm pretty sure that I executed what is written in "Microbial reference preparation" (making twice).
This is the content of my Taxonomy folder and the number of lines per each file:

  ```
    5986       accessionsTaxIDs.tab
  964319891 all.accession2taxid
    3407753   names.dmp
    2413365   nodes.dmp
    2413365   rankedlineage.dmp
```

Thank you.
Best,

Giuseppe

**Comment by gskoufos** [comment]
Hi,

That is weird; I mean the taxonomy files I downloaded yesterday have a slightly higher number of lines but that is expected since NCBI taxonomy is constantly getting bigger.

The error you're facing says that you are trying to access a value (in a python dictionary - hash table) using a key (i.e., 1546149) that is not part of the dictionary and thus the key error exception.

These keys are taken from the accessionsTaxIDs.tab file (which by the way is the only file in which we have the same number of lines). If you search this file, can you find the number 1546149 there?

Can you share your accessionsTaxIDs.tab file with me? you can temporary uploaded it somewhere (e.g., google drive) and send me a link!

Best,
Giorgos

**Comment by giuseppebenvenuto** [comment]
I already checked the presence of key value 1546149 in the accessionsTaxIDs.tab file.
Anyway, this is the link to the file:
https://drive.google.com/file/d/1DIWUTyH67J3b5T_zsjhfzvK_wD69t10g/view?usp=sharing

Thank you

**Comment by gskoufos** [comment]
I'm not really sure how this happened but I think I found what's causing the issue!

Can you please open your accessionsTaxIDs.tab file and replace 1546149 with 164759?

Then run the snakemake command again and if you didn't delete the output from pufferfish/cedar, it will automatically continue after the last successful step (i.e., quantification).

Let me know if that solved your issue!

Best,
Giorgos

**Comment by giuseppebenvenuto** [comment]
It perfectly works!
Thank you for your precious support.

Best,
Giuseppe

**Comment by gskoufos** [comment]
Anytime!

Best,
Giorgos
